name: Update Formula
on: [workflow_dispatch]
jobs:
  generate_formula:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Generate formula
      run: |
         ./.github/generate-formula.sh --install
      shell: sh
    - name: Commit changes
      uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b # Version 9.1.1
      with:
        default_author: github_actions
        message: 'Release latest version'
        add: 'Formula/klog.rb'
